package com.devwithzachary.mineserve.model

import kotlinx.serialization.Serializable

@Serializable
data class ServerProperties(
    val motd: String = "A MineServe Minecraft Server",
    val serverPort: Int = 25565,
    val maxPlayers: Int = 20,
    val gamemode: String = "survival",
    val difficulty: String = "normal",
    val pvp: Boolean = true,
    val hardcore: Boolean = false,
    val onlineMode: Boolean = true,
    val whiteList: Boolean = false,
    val enableCommandBlock: Boolean = true,
    val spawnMonsters: Boolean = true,
    val spawnAnimals: Boolean = true,
    val spawnNpcs: Boolean = true,
    val allowFlight: Boolean = false,
    val allowNether: Boolean = true,
    val viewDistance: Int = 10,
    val simulationDistance: Int = 8,
    val levelName: String = "world",
    val levelSeed: String = "",
    val levelType: String = "DEFAULT",
    val forceGamemode: Boolean = false,
    val enforceWhitelist: Boolean = false,
    val enableRcon: Boolean = false,
    val rconPassword: String = "",
    val rconPort: Int = 25575,
    val maxWorldSize: Int = 29999984,
    val syncChunkWrites: Boolean = true,
    val customProperties: Map<String, String> = emptyMap()
) {
    fun toPropertiesFileContent(mcVersion: String? = null): String = buildString {
        val isLegacy = mcVersion != null && compareMinecraftVersions(mcVersion, "1.13") < 0
        val effectiveGamemode = if (isLegacy) {
            when (gamemode.lowercase()) {
                "survival" -> "0"
                "creative" -> "1"
                "adventure" -> "2"
                "spectator" -> "3"
                else -> gamemode
            }
        } else gamemode

        val effectiveDifficulty = if (isLegacy) {
            when (difficulty.lowercase()) {
                "peaceful" -> "0"
                "easy" -> "1"
                "normal" -> "2"
                "hard" -> "3"
                else -> difficulty
            }
        } else difficulty

        val effectiveLevelType = if (isLegacy && (levelType.equals("minecraft:normal", ignoreCase = true) || levelType.isBlank())) {
            "DEFAULT"
        } else levelType

        appendLine("# Minecraft server properties generated by MineServe")
        appendLine("# ${java.util.Date()}")
        appendLine("motd=${escapeProperty(motd)}")
        appendLine("server-port=$serverPort")
        appendLine("max-players=$maxPlayers")
        appendLine("gamemode=$effectiveGamemode")
        appendLine("difficulty=$effectiveDifficulty")
        appendLine("pvp=$pvp")
        appendLine("hardcore=$hardcore")
        appendLine("online-mode=$onlineMode")
        appendLine("white-list=$whiteList")
        appendLine("enforce-whitelist=$enforceWhitelist")
        appendLine("enable-command-block=$enableCommandBlock")
        appendLine("spawn-monsters=$spawnMonsters")
        appendLine("spawn-animals=$spawnAnimals")
        appendLine("spawn-npcs=$spawnNpcs")
        appendLine("allow-flight=$allowFlight")
        appendLine("allow-nether=$allowNether")
        appendLine("view-distance=$viewDistance")
        appendLine("simulation-distance=$simulationDistance")
        appendLine("level-name=$levelName")
        appendLine("level-seed=$levelSeed")
        appendLine("level-type=$effectiveLevelType")
        appendLine("force-gamemode=$forceGamemode")
        appendLine("enable-rcon=$enableRcon")
        if (enableRcon) {
            appendLine("rcon.password=$rconPassword")
            appendLine("rcon.port=$rconPort")
        }
        appendLine("max-world-size=$maxWorldSize")
        appendLine("sync-chunk-writes=$syncChunkWrites")

        for ((key, value) in customProperties) {
            if (!isStandardKey(key)) {
                appendLine("$key=$value")
            }
        }
    }

    private fun escapeProperty(str: String): String {
        return str.replace("\\", "\\\\").replace("\n", "\\n")
    }

    companion object {
        private fun isStandardKey(key: String): Boolean {
            return key in setOf(
                "motd", "server-port", "max-players", "gamemode", "difficulty",
                "pvp", "hardcore", "online-mode", "white-list", "enforce-whitelist",
                "enable-command-block", "spawn-monsters", "spawn-animals", "spawn-npcs",
                "allow-flight", "allow-nether", "view-distance", "simulation-distance",
                "level-name", "level-seed", "level-type", "force-gamemode",
                "enable-rcon", "rcon.password", "rcon.port", "max-world-size", "sync-chunk-writes"
            )
        }

        fun parse(content: String): ServerProperties {
            val props = mutableMapOf<String, String>()
            content.lines().forEach { line ->
                val trimmed = line.trim()
                if (trimmed.isNotEmpty() && !trimmed.startsWith("#") && !trimmed.startsWith("!")) {
                    val eqIdx = trimmed.indexOf('=')
                    if (eqIdx != -1) {
                        val key = trimmed.substring(0, eqIdx).trim()
                        val value = trimmed.substring(eqIdx + 1).trim()
                        props[key] = value
                    }
                }
            }

            val customs = props.filterKeys { !isStandardKey(it) }

            val parsedGamemode = props["gamemode"]?.let { raw ->
                when (raw.trim()) {
                    "0" -> "survival"
                    "1" -> "creative"
                    "2" -> "adventure"
                    "3" -> "spectator"
                    else -> raw.trim()
                }
            } ?: "survival"

            val parsedDifficulty = props["difficulty"]?.let { raw ->
                when (raw.trim()) {
                    "0" -> "peaceful"
                    "1" -> "easy"
                    "2" -> "normal"
                    "3" -> "hard"
                    else -> raw.trim()
                }
            } ?: "normal"

            return ServerProperties(
                motd = props["motd"] ?: "A MineServe Minecraft Server",
                serverPort = props["server-port"]?.toIntOrNull() ?: 25565,
                maxPlayers = props["max-players"]?.toIntOrNull() ?: 20,
                gamemode = parsedGamemode,
                difficulty = parsedDifficulty,
                pvp = parseBoolean(props["pvp"], true),
                hardcore = parseBoolean(props["hardcore"], false),
                onlineMode = parseBoolean(props["online-mode"], true),
                whiteList = parseBoolean(props["white-list"], false),
                enforceWhitelist = parseBoolean(props["enforce-whitelist"], false),
                enableCommandBlock = parseBoolean(props["enable-command-block"], true),
                spawnMonsters = parseBoolean(props["spawn-monsters"], true),
                spawnAnimals = parseBoolean(props["spawn-animals"], true),
                spawnNpcs = parseBoolean(props["spawn-npcs"], true),
                allowFlight = parseBoolean(props["allow-flight"], false),
                allowNether = parseBoolean(props["allow-nether"], true),
                viewDistance = props["view-distance"]?.toIntOrNull() ?: 10,
                simulationDistance = props["simulation-distance"]?.toIntOrNull() ?: 8,
                levelName = props["level-name"] ?: "world",
                levelSeed = props["level-seed"] ?: "",
                levelType = props["level-type"]?.takeIf { it.isNotBlank() } ?: "DEFAULT",
                forceGamemode = parseBoolean(props["force-gamemode"], false),
                enableRcon = parseBoolean(props["enable-rcon"], false),
                rconPassword = props["rcon.password"] ?: "",
                rconPort = props["rcon.port"]?.toIntOrNull() ?: 25575,
                maxWorldSize = props["max-world-size"]?.toIntOrNull() ?: 29999984,
                syncChunkWrites = parseBoolean(props["sync-chunk-writes"], true),
                customProperties = customs
            )
        }

        private fun parseBoolean(value: String?, default: Boolean): Boolean {
            if (value == null) return default
            val trimmed = value.trim()
            return when {
                trimmed.equals("true", ignoreCase = true) || trimmed == "1" -> true
                trimmed.equals("false", ignoreCase = true) || trimmed == "0" -> false
                else -> default
            }
        }
    }
}
